# 站点基本信息
baseURL       = "https://xgd088.com/"
languageCode  = "zh-CN"
title         = "XDG088的博客"
theme         = "PaperMod"

# 主要内容类型
mainSections = ["posts"]

# 只禁用首页的RSS，其他页面保持默认
[outputs]
home = ["HTML"]

# 生产环境配置
[production]
  baseURL = "https://xgd088.com/"

# 开发环境配置
[development]
  baseURL = "http://localhost:1313/"

[params]
  # 明确设置PaperMod模式
  mode = "home-info" # 或者可以尝试 "regular" 
  
  ShowToc = true
  TocOpen = false
  TocLabel = "目录"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowFullTextinRSS = false
  ShowShareButtons = false
  ShowRssButtonInSectionTermList = false
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  header = { enable = false }
  
  # 首页模式设置
  [params.homeInfoParams]
    Title = "欢迎来到XDG088的博客"
    Content = "为世界的明天出一份力。"
  
  # 目录配置
  [params.toc]
    enable = true
    keepStatic = false
    auto = true
    number = true
    wrap = true
    expand = true

