# 站点基本信息
baseURL       = "https://my-hugo-blog-wu-mingyangs-projects.vercel.app/"  # 修改为您的 Vercel 域名
languageCode  = "zh-CN"
title         = "XDG088的博客"
theme         = "PaperMod"

[params]
  ShowToc = true
  TocOpen = false
  TocLabel = "目录"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowFullTextinRSS = true
  ShowShareButtons = false
  ShowRssButtonInSectionTermList = false
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  header = { enable = false }
  
  # 目录配置
  [params.toc]
    enable = true
    keepStatic = false
    auto = true
    number = true
    wrap = true
    expand = true

# 生产环境配置
[production]
  baseURL = "https://xdg088.vercel.app/"  # 修改为您的 Vercel 域名

# 开发环境配置
[development]
  baseURL = "http://localhost:1313/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 3

