# 站点基本信息
baseURL       = "https://my-hugo-blog-wu-mingyangs-projects.vercel.app/"
languageCode  = "zh-CN"
title         = "XDG088的博客"
theme         = "PaperMod"

# 输出格式配置 - HTML优先，RSS次之
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  
[outputFormats]
  [outputFormats.RSS]
    baseName = "index"
    mediaType = "application/rss+xml"

# 生产环境配置
[production]
  baseURL = "https://my-hugo-blog-wu-mingyangs-projects.vercel.app/"

# 开发环境配置
[development]
  baseURL = "http://localhost:1313/"

[params]
  ShowToc = true
  TocOpen = false
  TocLabel = "目录"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowFullTextinRSS = false
  ShowShareButtons = false
  ShowRssButtonInSectionTermList = false
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  header = { enable = false }
  
  # 首页模式设置
  [params.homeInfoParams]
    Title = "欢迎来到XDG088的博客"
    Content = "为世界的明天出一份力。"
  
  # 目录配置
  [params.toc]
    enable = true
    keepStatic = false
    auto = true
    number = true
    wrap = true
    expand = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 3

